---
- name: Add Queue Subscriptions"
  block:
    - name: "Creating Queue subscription {{ q }}::{{ topic }}"
      uri:
        url: "http://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns/{{ vpn }}/queues/{{ q }}/subscriptions"
        method: POST
        user: "{{ semp_username }}"
        password: "{{ semp_password }}"
        headers:
          Content-Type: "application/json"
        body:
          subscriptionTopic: "{{ topic }}"
        body_format: json
        force_basic_auth: yes
        status_code: 200,400
        return_content: yes
      register: result
      #ignore_errors: True
      #retries: 3
      #delay: 10

  # always:
  #  - name: "Script Results"
  #    debug:
  #        var: result

- name: Response
  debug:
   var: result.json.meta.error.status
  when: result.json.meta.responseCode != 200
